/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as TempoCalendarRouteImport } from './routes/tempo-calendar'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as JiraRouteImport } from './routes/jira'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CommitsRouteImport } from './routes/commits'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExtensionRouteImport } from './routes/api.extension'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TempoCalendarRoute = TempoCalendarRouteImport.update({
  id: '/tempo-calendar',
  path: '/tempo-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const JiraRoute = JiraRouteImport.update({
  id: '/jira',
  path: '/jira',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitsRoute = CommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionRoute = ApiExtensionRouteImport.update({
  id: '/api/extension',
  path: '/api/extension',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/commits': typeof CommitsRoute
  '/history': typeof HistoryRoute
  '/jira': typeof JiraRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/tempo-calendar': typeof TempoCalendarRoute
  '/test': typeof TestRoute
  '/api/extension': typeof ApiExtensionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/commits': typeof CommitsRoute
  '/history': typeof HistoryRoute
  '/jira': typeof JiraRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/tempo-calendar': typeof TempoCalendarRoute
  '/test': typeof TestRoute
  '/api/extension': typeof ApiExtensionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/commits': typeof CommitsRoute
  '/history': typeof HistoryRoute
  '/jira': typeof JiraRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/tempo-calendar': typeof TempoCalendarRoute
  '/test': typeof TestRoute
  '/api/extension': typeof ApiExtensionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calendar'
    | '/commits'
    | '/history'
    | '/jira'
    | '/settings'
    | '/summary'
    | '/tempo-calendar'
    | '/test'
    | '/api/extension'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calendar'
    | '/commits'
    | '/history'
    | '/jira'
    | '/settings'
    | '/summary'
    | '/tempo-calendar'
    | '/test'
    | '/api/extension'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calendar'
    | '/commits'
    | '/history'
    | '/jira'
    | '/settings'
    | '/summary'
    | '/tempo-calendar'
    | '/test'
    | '/api/extension'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalendarRoute: typeof CalendarRoute
  CommitsRoute: typeof CommitsRoute
  HistoryRoute: typeof HistoryRoute
  JiraRoute: typeof JiraRoute
  SettingsRoute: typeof SettingsRoute
  SummaryRoute: typeof SummaryRoute
  TempoCalendarRoute: typeof TempoCalendarRoute
  TestRoute: typeof TestRoute
  ApiExtensionRoute: typeof ApiExtensionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tempo-calendar': {
      id: '/tempo-calendar'
      path: '/tempo-calendar'
      fullPath: '/tempo-calendar'
      preLoaderRoute: typeof TempoCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jira': {
      id: '/jira'
      path: '/jira'
      fullPath: '/jira'
      preLoaderRoute: typeof JiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commits': {
      id: '/commits'
      path: '/commits'
      fullPath: '/commits'
      preLoaderRoute: typeof CommitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension': {
      id: '/api/extension'
      path: '/api/extension'
      fullPath: '/api/extension'
      preLoaderRoute: typeof ApiExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalendarRoute: CalendarRoute,
  CommitsRoute: CommitsRoute,
  HistoryRoute: HistoryRoute,
  JiraRoute: JiraRoute,
  SettingsRoute: SettingsRoute,
  SummaryRoute: SummaryRoute,
  TempoCalendarRoute: TempoCalendarRoute,
  TestRoute: TestRoute,
  ApiExtensionRoute: ApiExtensionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
