/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CommitsRouteImport } from './routes/commits'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExtensionRouteImport } from './routes/api.extension'

const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitsRoute = CommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionRoute = ApiExtensionRouteImport.update({
  id: '/api/extension',
  path: '/api/extension',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commits': typeof CommitsRoute
  '/history': typeof HistoryRoute
  '/summary': typeof SummaryRoute
  '/api/extension': typeof ApiExtensionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commits': typeof CommitsRoute
  '/history': typeof HistoryRoute
  '/summary': typeof SummaryRoute
  '/api/extension': typeof ApiExtensionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commits': typeof CommitsRoute
  '/history': typeof HistoryRoute
  '/summary': typeof SummaryRoute
  '/api/extension': typeof ApiExtensionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/commits'
    | '/history'
    | '/summary'
    | '/api/extension'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/commits' | '/history' | '/summary' | '/api/extension'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/commits'
    | '/history'
    | '/summary'
    | '/api/extension'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommitsRoute: typeof CommitsRoute
  HistoryRoute: typeof HistoryRoute
  SummaryRoute: typeof SummaryRoute
  ApiExtensionRoute: typeof ApiExtensionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commits': {
      id: '/commits'
      path: '/commits'
      fullPath: '/commits'
      preLoaderRoute: typeof CommitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension': {
      id: '/api/extension'
      path: '/api/extension'
      fullPath: '/api/extension'
      preLoaderRoute: typeof ApiExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommitsRoute: CommitsRoute,
  HistoryRoute: HistoryRoute,
  SummaryRoute: SummaryRoute,
  ApiExtensionRoute: ApiExtensionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
